# -*- mode: ruby -*-
# vi: set ft=ruby :

# Template environment for all of my vagrant vms. 
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # found box on this site: https://app.vagrantup.com/bento/boxes/ubuntu-16.04
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "laravel_project"

  # opens port 80 on the vm, and sets it to 8080 for the host.
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # command below syncs the files to the virtual machine. nice.
  config.vm.synced_folder "project_folder", "/home/vagrant/project_folder", type: "nfs"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # provision script, install all necessary items here
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && sleep 1
    apt-get upgrade -y
    apt-get install -y apache2 php libapache2-mod-php php-mcrypt php-mysql php7.0-zip && sleep 1
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    cd && php /home/vagrant/composer.phar global require "laravel/installer"
    cd / && sed -i -e 's/\r$//' ./vagrant/vagrant_configs/post_installation.bash
    sudo ./vagrant/vagrant_configs/post_installation.bash
  SHELL
end
