# -*- mode: ruby -*-
# vi: set ft=ruby :

# Template environment for all of my vagrant vms. 
Vagrant.configure("2") do |config|

  # found box on this site: https://app.vagrantup.com/bento/boxes/ubuntu-16.04
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "laravel-project"

  # opens port 80 on the vm, and sets it to 8080 for the host.
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # command below syncs the files to the virtual machine. nice.
  config.vm.synced_folder "project_folder", "/app/project_folder", type: "nfs"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # provision script, install all necessary items here
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && sleep 1 && apt-get upgrade -y
    apt-get install -y apache2 php libapache2-mod-php php-mcrypt php-mysql php7.0-zip php-mbstring php-xml && sleep 1
    sudo a2enmod rewrite
    sudo service apache2 restart
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');" && sleep 1 && mv composer.phar /usr/local/bin/composer
    echo "mysql-server mysql-server/root_password password root" | sudo debconf-set-selections
    echo "mysql-server mysql-server/root_password_again password root" | sudo debconf-set-selections
    apt-get install -y mysql-server
    sed -i 's/127\.0\.0\.1/0\.0\.0\.0/g' /etc/mysql/my.cnf
    mysql -uroot -p -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root" AND `Host`="localhost"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; FLUSH PRIVILEGES;'
    service mysql restart
    cd / && sed -i -e 's/\r$//' ./vagrant/vagrant_configs/post_installation.bash
    sudo ./vagrant/vagrant_configs/post_installation.bash
    echo "alias laravel='composer create-project --prefer-dist laravel/laravel'" >> /home/vagrant/.profile
    source /home/vagrant/.profile
    echo "System successfully installed. Everything is good to go! Type vagrant ssh to go into your vm."
    echo "To create a new laravel project, just run 'laravel <project_name> and it will be created for you."
    echo "Project is accessible from 192.168.33.10 from your browser."
    echo "Your MySQL username is 'root' and password is also 'root'"
  SHELL
end
