# -*- mode: ruby -*-
# vi: set ft=ruby :

# Template environment for all of my vagrant vms. 
Vagrant.configure("2") do |config|


  ## Provision the web server machine.
  config.vm.define "apache2" do |apache2|
    # debian stretchhhh
    apache2.vm.box = "debian/stretch64"
    apache2.vm.hostname = "apache-server"

    # opens port 80 on the vm, and sets it to 8080 for the host.
    apache2.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    apache2.vm.network "private_network", ip: "192.168.33.10"

    # command below syncs the files to the virtual machine. nice.
    apache2.vm.synced_folder "~/Projects/code", "/app/projects", type: "nfs"

    #
    apache2.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end

    # provision script, install all necessary items here
    apache2.vm.provision "shell", inline: <<-SHELL
      apt-get update && sleep 1 && apt-get upgrade -y
      apt-get install -y apache2 php libapache2-mod-php php-mysql php-zip php-mbstring php-xml && sleep 1
      sudo a2enmod rewrite
      sudo service apache2 restart
      cd / && sed -i -e 's/\r$//' ./vagrant/vagrant_configs/post_installation.bash
      sudo bash /vagrant/vagrant_configs/post_installation.bash
    SHELL
  end


  ## Provision the mysql database.
  config.vm.define "mariadb" do |mariadb|
    # moar debiannnn
    mariadb.vm.box = "debian/stretch64"
    mariadb.vm.hostname = "mysql-db"

    # opens port 80 on the vm, and sets it to 8080 for the host.
    mariadb.vm.network "forwarded_port", guest: 3306, host: 3307, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    mariadb.vm.network "private_network", ip: "192.168.33.11"

    #
    mariadb.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end

    # provision script, install all necessary items here
    mariadb.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get update && sleep 1 && apt-get upgrade -y

      apt-get install --assume-yes mysql-server mysql-client
      sudo mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY '12345';"
      sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';"
    SHELL
  end

end
