# -*- mode: ruby -*-
# vi: set ft=ruby :

# Template environment for all of my vagrant vms. 
Vagrant.configure("2") do |config|

  # found box on this site: https://app.vagrantup.com/bento/boxes/ubuntu-16.04
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "ubuntu-development"

  # opens port 80 on the vm, and sets it to 8080 for the host.
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # command below syncs the files to the virtual machine. nice.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # provision script, install all necessary items here
  config.vm.provision "shell", inline: <<-SHELL
    apt update && sleep 1 && apt upgrade -y
  SHELL
end
